{% set name = "ethos_penalps" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/FZJ-IEK3-VSA/ETHOS_PeNALPS/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2ca9f756e17ab5aaeba7252803b5b30362950e7f6e0b2a05b558923f99f2c222


build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >64.0.0
    - wheel
  run:
    - python >=3.10
    - pandas
    - jupyter-book
    - sphinx-autoapi
    - graphviz
    - python-graphviz
    - numpy >1.23.5
    - sqlalchemy <2.0
    - plotly
    - networkx
    - openpyxl
    - xlsxwriter
    - prospector
    - matplotlib-base
    - pytest >7.0
    - pip >=21.3
    - black
    - pint
    - proplot
    - datapane
    - svglib
    - cloudpickle
    - seaborn
    - workalendar
    - datetimerange
    - tectonic
    - typeguard
    - dataclasses-json
    - jsonpickle
    - pdf2image

test:
  imports:
    - ethos_penalps
    - pandas
  source_files:
    - .
  requires:
    - pytest
  commands:
    - pytest

about:
  home: https://github.com/FZJ-IEK3-VSA/ETHOS_PeNALPS
  summary: "A package to simulate energy load profiles of industrial manufacturing processes"
  license: AGPL-3.0-only
  license_file: LICENSE.txt
  doc_url: http://ethospenalps.readthedocs.io/
  dev_url: https://github.com/FZJ-IEK3-VSA/ETHOS_PeNALPS

extra:
  recipe-maintainers:
    - julian-belina
